### ISSUE TITLE
Clarify Readme

### ISSUE THREAD

**Issue by bigorangemachine** [patrickcrocker/cf-cli-resource#13]
Could we clarify the readme?

```
- put: cf-create-org-and-space
    resource: cf-env
```

Its not a clear example on how `cf-create-org-and-space` is declared.  What is it resource type?

**Comment by patrickcrocker** [comment]
Checkout the new note in the Multiple Command Syntax section and see if that helps (reopen this issue if it doesn't make sense!)

**Comment by bigorangemachine** [comment]
Hey @patrickcrocker thanks but it doesn't help.

When I implemented a 'cf-create-or-and-space' I get that its not declared as a resource type.  I'm not sure what it is I am doing wrong.  I thought that maybe there was a line missing from your sample; but based on what you updated in the README.md I am just as confused from when I started.

**Comment by patrickcrocker** [comment]
In the [Source Configuration](https://github.com/patrickcrocker/cf-cli-resource#source-configuration) section of the readme, we define the name of our resource as `cf-env`:
```yml
resources:
- name: cf-env
  type: cf-cli-resource
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    skip_cert_check: true
```

We are simply providing a different logical name for the `put` instead of using the resource name `cf-env`.  This is a matter of style preference so that when you view the job in the UI or hijack the container that you know that you are seeing the `cf-create-org` or the `cf-create-space` step.

The [Concourse docs](http://concourse.ci/put-step.html) discuss this logical renaming.
```yml
  - put: cf-create-org
    resource: cf-env
    params:
      command: create-org
      org: myorg
  - put: cf-create-space
    resource: cf-env
    params:
      command: create-space
      org: myorg
      space: myspace
```

If this is confusing, then you can simply just use the resource `cf-env` as the `put` name:
```yml
  - put: cf-env
    params:
      command: create-org
      org: myorg
  - put: cf-env
    params:
      command: create-space
      org: myorg
      space: myspace
```

In this case you would see two `cf-env` steps in your job and would need to click deeper to know which cf-cli command was used.
