### ISSUE TITLE
zero-downtime-push can not find docker registry password

### ISSUE THREAD

**Issue by r-chris** [patrickcrocker/cf-cli-resource#23]
Hi, I am trying to use this resource to get zero-downtime deploys working. Unfortunately, I am receiving this error:

```
[INFO] cf version 6.32.0+0191c33d9.2017-09-26
Setting api endpoint to https://api*****...
OK

api endpoint:   https://api*****
api version:    2.100.0
Not logged in. Use 'cf login' to log in.
API endpoint: https://api*****
Authenticating...
OK
Use 'cf target' to view or set your target org and space.
[INFO] Executing zero-downtime-push:staging
api endpoint:   https://api.lyra-836.appcloud.swisscom.com
api version:    2.100.0
user:           ***@***
org:            ***
space:          Staging
Renaming app staging to staging-venerable in org **** / space Staging as ***@***...
OK
Using manifest file git/cf/manifest-stage.yml

Deleting app staging in org *** / space Staging as ***@***...
OK
App staging does not exist.
Renaming app staging-venerable to staging in org *** / space Staging as ***@***...
OK
error: No Docker password was provided. Please provide the password by setting the CF_DOCKER_PASSWORD environment variable.
```

My put section looks like this and includes the `CF_DOCKER_PASSWORD ` inside the `environment_variables` parameters. This was working before I tried to switch from the build in `cf-resource`.

```
  - put: deploy-staging
    params:
      command: zero-downtime-push
      manifest: git/cf/manifes-stage.yml
      current_app_name:staging
      environment_variables:
        ENVIRONMENT: staging
        CF_DOCKER_PASSWORD: ((docker-registry-password))
```

Thanks for any help.
